name: Code Quality Checks

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'vite.config.*'
      - 'tsconfig.*'
      - 'index.html'
      - 'env.d.ts'
      - '.eslintrc.*'
      - '.prettier*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: [eslint, markdownlint, prettier, typecheck]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-optional

      - name: Run ESLint
        if: matrix.check == 'eslint'
        run: npm run lint

      - name: Install and Run Markdownlint
        if: matrix.check == 'markdownlint'
        run: |
          npm install -g markdownlint-cli
          markdownlint '**/*.md' --ignore 'node_modules/**' --config .markdownlint.json

      - name: Run Prettier
        if: matrix.check == 'prettier'
        run: npx prettier --check .

      - name: Run TypeScript type check
        if: matrix.check == 'typecheck'
        run: npm run type-check